name: zekfad_lints
description: Set of lints for Flutter applications, widget collections, Dart applications and packages.
version: 2.3.0
homepage: https://github.com/Zekfad/dart_lints
repository: https://github.com/Zekfad/dart_lints
issue_tracker: https://github.com/Zekfad/dart_lints/issues

environment:
  sdk: ^3.6.0

dependencies:
  lints: '>=5.0.0 <7.0.0'
  flutter_lints: ^5.0.0
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.
